<a href="https://colab.research.google.com/github/krmohit0026/first_project/blob/master/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
- numpy = numerical python

- foundational package in python , which is built on C - hence fast
- Travis Oliphant in 2005
- core data structure is N-dimensional array (ndarray)
- 10x to 100x faster as compared to lists
- contiguous memory , is cache friendly
- can perform operations on different array shapes.

In [2]:
import numpy as np
import time

size = 1_000_000

python_list = list(range(size))
numpy_array = np.arange(size)

# python list operation
start=time.time()
python_result = [x * 2 for x in python_list]
python_time = time.time() - start

# numpy operation
start = time.time()
numpy_result = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list time : {python_time :.4f} seconds")
print(f"Numpy array time : {numpy_time :.4f} seconds")

Python list time : 0.0353 seconds
Numpy array time : 0.0022 seconds


In [3]:
# convertng list to array

list_a = [1,2,3,4,5]
print(list_a)
numpy_arr = np.array(list_a)
print(numpy_arr) # this is a 1-D array

# to get the dimensions of an array , use .ndim()
print(f"Dimensions of numpy array here are : {numpy_arr.ndim}")

[1, 2, 3, 4, 5]
[1 2 3 4 5]
Dimensions of numpy array here are : 1


In [4]:
# creating 1D, 2D and 3D array objects from lists in numpy

print("Creating numpy arrays from lists.....\n")

arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])

arr_2d = np.array([[1,2,3] ,
                    [4,5,6]]) # this is a 2x3 matrix

arr_3d = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])

print(f"1D array : {arr_1d} , shape : {arr_1d.shape} , dim: {arr_1d.ndim}")
print(f"2D array : {arr_2d} , shape : {arr_2d.shape}, dim: {arr_2d.ndim}")
print(f"3D array : {arr_3d} , shape : {arr_3d.shape}, dim: {arr_3d.ndim}")

Creating numpy arrays from lists.....

1D array : [ 1  2  3  4  5  6  7  8  9 10] , shape : (10,) , dim: 1
2D array : [[1 2 3]
 [4 5 6]] , shape : (2, 3), dim: 2
3D array : [[[1 2 3]
  [4 5 6]
  [7 8 9]]] , shape : (1, 3, 3), dim: 3


In [5]:
# image representation using numpy array

print("Image representation..\n")

# colourful image ; r,g,b : range of pixel : 0-255

tiny_image = np.array([
    [[255, 0, 0],   [0, 255, 0],   [0, 0, 255]],    # Row 1: Red, Green, Blue
    [[255, 255, 0], [255, 0, 255], [0, 255, 255]],  # Row 2: Yellow, Magenta, Cyan
    [[128, 128, 128], [0, 0, 0],   [255, 255, 255]] # Row 3: Gray, Black, White
])

print(f"Image shape:{tiny_image.shape}")
print(f"Image dtype : {tiny_image.dtype}")
print(f"First Pixel : {tiny_image[0,0]}")

Image representation..

Image shape:(3, 3, 3)
Image dtype : int64
First Pixel : [255   0   0]


In [6]:
# built in array generators

# populate the matrix with 0's in the defined shape
zeroes_matrix = np.zeros((3,4))

print(zeroes_matrix)

# populate the matrix with 1's in the defined shape
ones_matrix = np.ones((5,5))

print(ones_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# arange : like python's range but returns an array

arr_range = np.arange(0,10)

print(arr_range)

print("----------------------------")

arr_range_2 = np.arange(3,42)

print(arr_range_2)

print("--------------using step size : example 1--------------")
# step size is the difference
# syntax : np.arange(start,stop,step)

arr_range_3 = np.arange(0,10,2)

print(arr_range_3)

print("--------------using step size : example 2--------------")

arr_range_4 = np.arange(11,60,4)

print(arr_range_4)

[0 1 2 3 4 5 6 7 8 9]
----------------------------
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
--------------using step size : example 1--------------
[0 2 4 6 8]
--------------using step size : example 2--------------
[11 15 19 23 27 31 35 39 43 47 51 55 59]


In [8]:
# linspace : evenly spaced numbers over interval

arr_linspace = np.linspace(0,10,3)
print(arr_linspace)

arr_linspace_2 = np.linspace(0,15,6)
print(arr_linspace_2)

arr_linspace_3 = np.linspace(0,1,7)
print(arr_linspace_3)

[ 0.  5. 10.]
[ 0.  3.  6.  9. 12. 15.]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [9]:
import pandas as pd

df = pd.read_csv("sales_raw.csv")


In [10]:
print("=== DATASET INSPECTION ===")
print(f"Shape: {df.shape}")
print(f"\nData types:\n{df.dtypes}")
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nFirst few rows:\n{df.head()}")
print(f"\nDuplicate rows: {df.duplicated().sum()}")


=== DATASET INSPECTION ===
Shape: (6, 5)

Data types:
order_id      int64
region       object
product      object
quantity    float64
price         int64
dtype: object

Missing values:
order_id    0
region      0
product     0
quantity    1
price       0
dtype: int64

First few rows:
   order_id region   product  quantity  price
0      4001   East  Keyboard       2.0   1500
1      4002   West     Mouse       NaN    500
2      4003   East   Monitor       1.0  12000
3      4004  South  Keyboard       1.0   1500
4      4005   West   Monitor       2.0  12000

Duplicate rows: 1


In [11]:
print(f"Rows before removing duplicates: {len(df)}")
df_clean = df.drop_duplicates()
print(f"Rows after removing duplicates: {len(df_clean)}")


Rows before removing duplicates: 6
Rows after removing duplicates: 5


In [12]:
print(f"\nRows before dropping missing quantity: {len(df_clean)}")
df_clean = df_clean.dropna(subset=["quantity"])
print(f"Rows after dropping missing quantity: {len(df_clean)}")



Rows before dropping missing quantity: 5
Rows after dropping missing quantity: 4


In [13]:
df_clean["quantity"] = pd.to_numeric(df_clean["quantity"], errors='coerce')
df_clean["price"] = pd.to_numeric(df_clean["price"], errors='coerce')

print("\n=== DATA TYPES AFTER CLEANING ===")
print(df_clean.dtypes)



=== DATA TYPES AFTER CLEANING ===
order_id      int64
region       object
product      object
quantity    float64
price         int64
dtype: object


In [14]:
print("\n=== CLEANING VERIFICATION ===")
print(f"Missing values:\n{df_clean.isnull().sum()}")
print(f"Duplicates: {df_clean.duplicated().sum()}")
print(f"\nCleaned dataset:\n{df_clean}")



=== CLEANING VERIFICATION ===
Missing values:
order_id    0
region      0
product     0
quantity    0
price       0
dtype: int64
Duplicates: 0

Cleaned dataset:
   order_id region   product  quantity  price
0      4001   East  Keyboard       2.0   1500
2      4003   East   Monitor       1.0  12000
3      4004  South  Keyboard       1.0   1500
4      4005   West   Monitor       2.0  12000


In [15]:
df_clean["revenue"] = df_clean["quantity"] * df_clean["price"]
print("Dataset with revenue:")
print(df_clean)


Dataset with revenue:
   order_id region   product  quantity  price  revenue
0      4001   East  Keyboard       2.0   1500   3000.0
2      4003   East   Monitor       1.0  12000  12000.0
3      4004  South  Keyboard       1.0   1500   1500.0
4      4005   West   Monitor       2.0  12000  24000.0


In [16]:
revenue_by_product = df_clean.groupby("product")["revenue"].sum().reset_index()
revenue_by_product.columns = ["product", "total_revenue"]
revenue_by_product = revenue_by_product.sort_values("total_revenue", ascending=False)

print("\n=== REVENUE BY PRODUCT ===")
print(revenue_by_product)



=== REVENUE BY PRODUCT ===
    product  total_revenue
1   Monitor        36000.0
0  Keyboard         4500.0


In [17]:
revenue_by_region = df_clean.groupby("region")["revenue"].sum().reset_index()
revenue_by_region.columns = ["region", "total_revenue"]
revenue_by_region = revenue_by_region.sort_values("total_revenue", ascending=False)

print("\n=== REVENUE BY REGION ===")
print(revenue_by_region)



=== REVENUE BY REGION ===
  region  total_revenue
2   West        24000.0
0   East        15000.0
1  South         1500.0


In [18]:
df_clean.to_csv("clean_sales.csv", index=False)
print("Saved: clean_sales.csv")


Saved: clean_sales.csv


In [19]:
revenue_by_product.to_csv("revenue_by_product.csv", index=False)
print("Saved: revenue_by_product.csv")


Saved: revenue_by_product.csv


In [20]:
revenue_by_region.to_csv("revenue_by_region.csv", index=False)
print("Saved: revenue_by_region.csv")


Saved: revenue_by_region.csv


In [21]:
print("\n=== SUMMARY ===")
print(f"Total records cleaned: {len(df_clean)}")
print(f"Total revenue: {df_clean['revenue'].sum():,.2f}")
print(f"Products analyzed: {len(revenue_by_product)}")
print(f"Regions analyzed: {len(revenue_by_region)}")



=== SUMMARY ===
Total records cleaned: 4
Total revenue: 40,500.00
Products analyzed: 2
Regions analyzed: 3


In [22]:
def clean_and_aggregate_sales(input_file):
    """
    Clean sales data and generate revenue summaries.
    """
    # Load data
    df = pd.read_csv(input_file)
    print(f"Loaded {len(df)} records")

    # Clean data
    df_clean = df.drop_duplicates()
    df_clean = df_clean.dropna(subset=["quantity"])
    df_clean["quantity"] = pd.to_numeric(df_clean["quantity"], errors='coerce')
    df_clean["price"] = pd.to_numeric(df_clean["price"], errors='coerce')

    # Calculate revenue
    df_clean["revenue"] = df_clean["quantity"] * df_clean["price"]

    # Aggregations
    revenue_by_product = df_clean.groupby("product")["revenue"].sum().reset_index()
    revenue_by_product.columns = ["product", "total_revenue"]
    revenue_by_product = revenue_by_product.sort_values("total_revenue", ascending=False)

    revenue_by_region = df_clean.groupby("region")["revenue"].sum().reset_index()
    revenue_by_region.columns = ["region", "total_revenue"]
    revenue_by_region = revenue_by_region.sort_values("total_revenue", ascending=False)

    # Save outputs
    df_clean.to_csv("clean_sales.csv", index=False)
    revenue_by_product.to_csv("revenue_by_product.csv", index=False)
    revenue_by_region.to_csv("revenue_by_region.csv", index=False)

    print("Cleaning and aggregation complete!")
    print(f"  - Clean records: {len(df_clean)}")
    print(f"  - Total revenue: {df_clean['revenue'].sum():,.2f}")

    return df_clean, revenue_by_product, revenue_by_region


In [23]:
clean_df, product_rev, region_rev = clean_and_aggregate_sales("sales_raw.csv")


Loaded 6 records
Cleaning and aggregation complete!
  - Clean records: 4
  - Total revenue: 40,500.00
